[tool.black]
line-length = 100
target-version = ["py38"]

[tool.isort]
profile = "black"
lines_after_imports = 2
line_length = 100
py_version = "38"
known_future_od = "future_od"
known_torch = ["torch", "torchvision"]
sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    # Separate out torch for convenience
    "TORCH",
    "FUTURE_OD",
    "FIRSTPARTY",
    "LOCALFOLDER",
]
# forced_separate = []
